# Generated by Django 4.2.2 on 2023-07-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_rename_name_party_partyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='Code',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
