# Generated by Django 4.2.2 on 2023-07-11 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_party_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='party',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parties.party'),
        ),
    ]
