# Generated by Django 4.2.2 on 2023-07-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_remove_party_host_alter_member_cost_alter_party_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='host',
            field=models.CharField(default='', max_length=100),
        ),
    ]
