# Generated by Django 4.2.2 on 2023-07-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0008_alter_party_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='menu',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
