# Generated by Django 4.2.2 on 2023-07-31 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
        ('parties', '0009_alter_party_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='orderList',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.restaurant'),
        ),
    ]
