# Generated by Django 4.2.2 on 2023-08-24 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parties', '0010_party_orderlist_alter_party_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='slipImage',
            field=models.ImageField(blank=True, null=True, upload_to='memberslip_images/'),
        ),
        migrations.AddField(
            model_name='party',
            name='promptPay',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='party',
            name='timeCreate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='party',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='party',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.restaurant'),
        ),
        migrations.AlterField(
            model_name='party',
            name='orderList',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
