# Generated by Django 4.2.2 on 2023-08-24 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parties', '0012_alter_party_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='host',
            new_name='hostID',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.AddField(
            model_name='member',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.CharField(blank=True, choices=[('F', 'Food&Drink'), ('H', 'Home&Hotel'), ('S', 'Subscribe&Service')], max_length=1),
        ),
    ]
